initial_configuration:
  map : SanFrancisco
  time_of_day : 17.0
  freeze_time_of_day  : true
  fog_intensity : 0.1
  rain_intensity : 0.6
  road_wetness : 0.5
  enable_traffic : true
  enable_pedestrian : true
  traffic_density : 300
vehicles : 
  - type : XE_Rigged-autoware
    address : localhost
    port : 9090
    command_type : twist // not supported yet
    enable_lidar : true
    enable_gps : true
    enable_main_camera : true
    enable_high_quality_rendering : true
    position : 
      n : 4140310.4   // Northing, Easting in UTM coordinates + Height 
      e : 590681.5    // Set to 0.0 to use the default position
      h : 10.1
    orientation : 
      r : 0.0
      p : 0.0
      y : 269.9